item_names = [
    "-",
    "Kaiser (Claw)",
    "CatClaw (Claw)",
    "Dragon (Claw)",
    "Elven (Claw)",
    "HellClaw (Claw)",
    "Nunchuck",
    "Tonfa (Nunchuck)",
    "3-Part (Nunchuck)",
    "Mithril (Rod)",
    "Flame (Rod)",
    "Ice (Rod)",
    "Light (Rod)",
    "Ultimate (Rod)",
    "Staff",
    "Burning (Staff)",
    "Freezing (Staff)",
    "Shining (Staff)",
    "Golem (Staff)",
    "Rune (Staff)",
    "Eldest (Staff)",
    "Hammer",
    "Thor (Hammer)",
    "Battle (Axe)",
    "Great Axe",
    "M. Star (Axe)",
    "Thunder (Spear)",
    "Wind (Spear)",
    "Blood (Spear)",
    "Holy (Spear)",
    "Knife",
    "Dagger",
    "Mithril (Knife)",
    "M. Gauche (Knife)",
    "Orialcon (Knife)",
    "Airknife",
    "Long (Sword)",
    "W. Slayer (Sword)",
    "Shiny (Sword)",
    "Mithril (Sword)",
    "Serpent (Sword)",
    "Ice Blade (Sword)",
    "Tyrving (Sword)",
    "Salamand (Sword)",
    "King (Sword)",
    "Tomahawk (Axe)",
    "Ancient (Sword)",
    "Ashura (Sword)",
    "Blood (Sword)",
    "Defender (Sword)",
    "Triton (Hammer)",
    "Kotetsu (Sword)",
    "Kiku (Sword)",
    "Break (Sword)",
    "Excalibur (Sword)",
    "Masamune (Sword)",
    "Ragnarök (Sword)",
    "Onion (Sword)",
    "Flame (Magic)",
    "Ice (Magic)",
    "Inferno (Magic)",
    "Light (Magic)",
    "Illumina (Magic)",
    "Boomerang (Throw)",
    "Full Moon (Throw)",
    "Shuriken (Throw)",
    "Blizzard (Magic)",
    "Giyaman (Bell)",
    "Earth (Bell)",
    "Rune (Bell)",
    "Madora (Harp)",
    "Dream (Harp)",
    "Lamia (Harp)",
    "Loki (Harp)",
    "Bow",
    "Great Bow",
    "Killer (Bow)",
    "Rune (Bow)",
    "Yoichi (Bow)",
    "Wooden (Bow)",
    "Holy (Arrow)",
    "Iron (Arrow)",
    "Bolt (Arrow)",
    "Fire (Arrow)",
    "Ice (Arrow)",
    "Medusa (Arrow)",
    "Yoichi (Arrow)",
    "**NULL**",
    "Leather (Shield)",
    "Onion (Shield)",
    "Mithril (Shield)",
    "Ice (Shield)",
    "Hero (Shield)",
    "Demon (Shield)",
    "Diamond (Shield)",
    "Aegis (Shield)",
    "Genji (Shield)",
    "Crystal (Shield)",
    "Leather (Helmet)",
    "Onion (Helmet)",
    "Mithril (Helmet)",
    "Carapace (Helmet)",
    "Ice (Helmet)",
    "Headband (Helmet)",
    "Scholar (Helmet)",
    "Darkhood (Helmet)",
    "Chakra (Helmet)",
    "Viking (Helmet)",
    "Dragon (Helmet)",
    "Feather (Helmet)",
    "Diamond (Helmet)",
    "Genji (Helmet)",
    "Crystal (Helmet)",
    "Ribbon (Helmet)",
    "Cloth (Armor)",
    "Leather (Armor)",
    "Onion (Armor)",
    "Mithril (Armor)",
    "Carapace (Armor)",
    "Ice (Armor)",
    "Flame Mail (Armor)",
    "Kenpo (Armor)",
    "Dark Suit (Armor)",
    "Wizard (Armor)",
    "Viking (Armor)",
    "Black Belt (Armor)",
    "Knight (Armor)",
    "Dragon (Armor)",
    "Bard (Armor)",
    "Scholar (Armor)",
    "Gaia (Armor)",
    "Demon (Armor)",
    "Diamond (Armor)",
    "Reflect (Armor)",
    "White Robe (Armor)",
    "Black Robe (Armor)",
    "Genji (Armor)",
    "Crystal (Armor)",
    "Rusted (Armor)",
    "Copper (Glove)",
    "Onion (Glove)",
    "Mithril (Glove)",
    "Mithril (Gauntlet)",
    "Thief (Glove)",
    "Gauntlet (Glove)",
    "Power (Glove)",
    "Rune (Glove)",
    "Diamond (Gauntlet)",
    "Diamond (Glove)",
    "Protect (Glove)",
    "Genji (Glove)",
    "Crystal (Glove)",
    "Magic Key",
    "Carrot",
    "Horn",
    "Eye",
    "Time Gear",
    "Eureka Key",
    "Wind Fang",
    "Fire Fang",
    "Water Fang",
    "Earth Fang",
    "Lute",
    "Sylx Key",
    "Midge Bread",
    "?",
    "Potion",
    "HiPotion",
    "Elixir",
    "Fenix Down",
    "Soft",
    "Maiden Kiss",
    "Echo Herb",
    "Luck Mallet",
    "Eyedrop",
    "Antidote",
    "Otter Head",
    "Bomb Shard",
    "South Wind",
    "Zeus' Rage",
    "BombR.Arm",
    "Northwind",
    "Gods' Rage",
    "Earth Drum",
    "Lamia Scl.",
    "Gods' Wine",
    "Turtle Shell",
    "Devil's Sigh",
    "Black Hole",
    "Dark Scent",
    "Lilith Kiss",
    "Imp's Yawn",
    "Split Shell",
    "Paralyzer",
    "Mute Charm",
    "Pillow",
    "Bomb Head",
    "Barrier",
    "Choco Rage",
    "White Scent",
    "Flare (Magic)",
    "Death (Magic)",
    "Meteo (Magic)",
    "Whirl Wind (Magic)",
    "Life 2 (Magic)",
    "Holy (Magic)",
    "Bahamut (Magic)",
    "Quake (Magic)",
    "Break 2 (Magic)",
    "Drain (Magic)",
    "Cure 4 (Magic)",
    "Heal (Magic)",
    "Wall (Magic)",
    "Levia (Magic)",
    "Fire 3 (Magic)",
    "Bio (Magic)",
    "Warp (Magic)",
    "Aero 2 (Magic)",
    "Soft (Magic)",
    "Haste (Magic)",
    "Odin (Magic)",
    "Bolt 3 (Magic)",
    "Kill (Magic)",
    "Erase (Magic)",
    "Cure 3 (Magic)",
    "Life (Magic)",
    "Safe (Magic)",
    "Titan (Magic)",
    "Break (Magic)",
    "Ice 3 (Magic)",
    "Shade (Magic)",
    "Libra (Magic)",
    "Confuse (Magic)",
    "Mute (Magic)",
    "Ifrit (Magic)",
    "Fire 2 (Magic)",
    "Ice 2 (Magic)",
    "Bolt 2 (Magic)",
    "Cure 2 (Magic)",
    "Exit (Magic)",
    "Wash (Magic)",
    "Ramuh (Magic)",
    "Bolt (Magic)",
    "Venom (Magic)",
    "Blind (Magic)",
    "Aero (Magic)",
    "Toad (Magic)",
    "Mini (Magic)",
    "Shiva (Magic)",
    "Fire (Magic)",
    "Ice (Magic)",
    "Sleep (Magic)",
    "Cure (Magic)",
    "Pure (Magic)",
    "Sight (Magic)",
    "Chocobo (Magic)"
]

world_names = [
    "Floating Continent",
    "Floating Continent B?",
    "Surface World (Flooded)",
    "Surface World",
    "Surface World (Underwater)"
]

job_names = [
    "Onion Kid",
    "Fighter",
    "Monk",
    "White Wizard",
    "Black Wizard",
    "Red Wizard",
    "Hunter",
    "Knight",
    "Thief",
    "Scholar",
    "Geomancer",
    "Dragoon",
    "Viking",
    "Karateka",
    "Magic Knight",
    "Conjurer",
    "Bard",
    "Warlock",
    "Shaman",
    "Summoner",
    "Sage",
    "Ninja"
]

follower_names = [
    "None",
    "Sara",
    "Cid",
    "Desh",
    "\"Shadow\"",
    "Elia",
    "Allus",
    "Dorga",
    "Unne"
]

crystal_levels = [
    "Job Menu Locked",
    "Wind Crystal",
    "Fire Crystal",
    "Water Crystal",
    "Earth Crystal",
    "Forbidden Land Eureka"
]
